root = "."
tmp_dir = "tmp"

[build]
  bin = "$(make build/path)"
  cmd = "make build"
  delay = 1000
  exclude_dir = ["vendor", "node_modules"]
  exclude_unchanged = true
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  kill_delay = 500
  log = "air.log"
  send_interrupt = true
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
