# fly.toml file generated for thousand on 2021-08-24T08:34:45+01:00

app = "thousand"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "bin/thousand migrate run"

[env]
  PORT = "8080"
  LOG_FORMAT = "prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  port = 9091
  path = "/metrics"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "2s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
