// Code generated by sqlc. DO NOT EDIT.
// source: skills.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (vampire_id, description)
    VALUES ($1, $2)
RETURNING
    id, vampire_id, description, created_at, updated_at
`

type CreateSkillParams struct {
	VampireID   uuid.UUID
	Description string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.VampireID, arg.Description)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.VampireID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillsForVampire = `-- name: GetSkillsForVampire :many
SELECT
    skills.id, skills.vampire_id, skills.description, skills.created_at, skills.updated_at
FROM
    skills
WHERE
    skills.vampire_id = $1
`

func (q *Queries) GetSkillsForVampire(ctx context.Context, vampireID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillsForVampire, vampireID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.VampireID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
