name: CI
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - run: go test ./...
        env:
          TMPDIR: ${{ runner.temp }}

  run_linter:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - uses: github/codeql-action/init@v1
        with:
          languages: go

      - uses: github/codeql-action/analyze@v1

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [run_tests, analyze]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
