name: CI
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - run: go test ./...
        env:
          TMPDIR: ${{ runner.temp }}

      - uses: superfly/flyctl-actions@1.1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
