name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - synchronize

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: thousand_test
          POSTGRES_PASSWORD: vampire
          POSTGRES_USER: vampire
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0

      - run: make ci
        env:
          DATABASE_URL: postgres://vampire:vampire@localhost:5432/thousand_test?sslmode=disable
          TMPDIR: ${{ runner.temp }}
          GOLANGCI_LINT_ARGS: --new-from-rev=origin/${{ github.base_ref || 'main' }} --out-format=github-actions

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [run_tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
